# Generated by Django 4.1.1 on 2022-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=True, verbose_name='Google User'),
        ),
    ]
