# Generated by Django 4.1.1 on 2022-10-07 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetcodeStartData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('leetcode_username', models.CharField(max_length=64, verbose_name='Leetcode Username')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions Solved')),
                ('easy_questions', models.IntegerField(default=0, verbose_name='Easy Questions Solved')),
                ('medium_questions', models.IntegerField(default=0, verbose_name='Medium Questions Solved')),
                ('hard_questions', models.IntegerField(default=0, verbose_name='Hard Questions Solved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leetcode Start Data',
                'verbose_name_plural': 'Leetcode Start Data',
            },
        ),
        migrations.CreateModel(
            name='LeetcodeUpdatedData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('leetcode_username', models.CharField(max_length=64, verbose_name='Leetcode Username')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions Solved')),
                ('easy_questions', models.IntegerField(default=0, verbose_name='Easy Questions Solved')),
                ('medium_questions', models.IntegerField(default=0, verbose_name='Medium Questions Solved')),
                ('hard_questions', models.IntegerField(default=0, verbose_name='Hard Questions Solved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leetcode Updated Data',
                'verbose_name_plural': 'Leetcode Updated Data',
            },
        ),
        migrations.CreateModel(
            name='LeetcodeDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions Solved')),
                ('easy_questions', models.IntegerField(default=0, verbose_name='Easy Questions Solved')),
                ('medium_questions', models.IntegerField(default=0, verbose_name='Medium Questions Solved')),
                ('hard_questions', models.IntegerField(default=0, verbose_name='Hard Questions Solved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Leetcode Data',
                'verbose_name_plural': 'Daily Leetcode Data',
            },
        ),
    ]
