# Generated by Django 4.1.1 on 2022-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeetcodeDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions Solved')),
                ('easy_questions', models.IntegerField(default=0, verbose_name='Easy Questions Solved')),
                ('medium_questions', models.IntegerField(default=0, verbose_name='Medium Questions Solved')),
                ('hard_questions', models.IntegerField(default=0, verbose_name='Hard Questions Solved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Leetcode Data',
                'verbose_name_plural': 'Daily Leetcode Data',
            },
        ),
        migrations.CreateModel(
            name='LeetcodeInitialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_username', models.CharField(max_length=64, verbose_name='Leetcode Username')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions Solved')),
                ('easy_questions', models.IntegerField(default=0, verbose_name='Easy Questions Solved')),
                ('medium_questions', models.IntegerField(default=0, verbose_name='Medium Questions Solved')),
                ('hard_questions', models.IntegerField(default=0, verbose_name='Hard Questions Solved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leetcode Initial Data',
                'verbose_name_plural': 'Leetcode Initial Data',
            },
        ),
        migrations.CreateModel(
            name='LeetcodeUpdatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_username', models.CharField(max_length=64, verbose_name='Leetcode Username')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions Solved')),
                ('easy_questions', models.IntegerField(default=0, verbose_name='Easy Questions Solved')),
                ('medium_questions', models.IntegerField(default=0, verbose_name='Medium Questions Solved')),
                ('hard_questions', models.IntegerField(default=0, verbose_name='Hard Questions Solved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leetcode Updated Data',
                'verbose_name_plural': 'Leetcode Updated Data',
            },
        ),
    ]
