# Generated by Django 4.1.1 on 2022-10-07 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeetcodeStartData',
            new_name='LeetcodeInitialData',
        ),
        migrations.AlterModelOptions(
            name='leetcodeinitialdata',
            options={'verbose_name': 'Leetcode Initial Data', 'verbose_name_plural': 'Leetcode Initial Data'},
        ),
    ]
